.PHONY: test-unit
.PHONY: test-options
.PHONY: test-desciptors

test-unit:
	python -m pytest tests/unit/

test-options:
	python -m pytest tests/unit/options/

test-desciptors:
	python -m pytest tests/unit/desciptors/
